Volumeマウントして、そこにデータを一時的に保持します。
kwacgit/kazy-english-class-notify pull request #16
Opened 2020-06-11 12:06 UTC by solaWat

LINEの通知がウザすぎたので、その場しのぎですが、差分比較します。

Issue : #1

2020-06-11 12:08 UTC, solaWat commented on notify/notify.py
> +            if file_content != messege:
`if message` の中に、`if file_content != messege:`があるのが気持ち悪い。これ一個にできんじゃないの

2020-06-13 12:18 UTC, KAZYPinkSaurus commented on notify/notify.py
> +            pass
りかい

2020-06-13 12:20 UTC, solaWat commented on notify/notify.py
> +            pass
この記事からもらってきました
https://note.nkmk.me/python-file-io-open-with/

むしろファイルがある時にキャッチしてる。

2020-06-13 12:20 UTC, KAZYPinkSaurus commented on notify/notify.py
> +            pass
僕も先程同じサイトを見ました

2020-06-13 13:16 UTC, solaWat commented on notify/notify.py
> +            if file_content != messege:
一個にしました 
https://github.com/smknhd-tech/english-class-notify/pull/16/commits/2bb9be01d40e97f8e363872905a34965f07626d3

2020-06-13 13:22 UTC, KAZYPinkSaurus requested changes

2020-06-13 13:22 UTC, KAZYPinkSaurus commented on notify/notify.py
> +            PythonNotify(f"@{user}" + messege + day.upper(), TOKEN)
if message の  message をなくして 予約なかったら 現在予約なしなどと PythonNotify関数でつぶやいてもらうこと出来る?

2020-06-13 13:22 UTC, KAZYPinkSaurus commented on notify/notify.py
> +                file_content = fr.read()
例外キャッチ使わずに
        if os.path.isfile(CONTENT_PATH):
            with open(CONTENT_PATH) as fr:
                    file_content = fr.read()
        else:
            file_content = ""

としていみるのもいいかも

2020-06-13 13:35 UTC, solaWat commented on notify/notify.py
> +                file_content = fr.read()
そっちもいいね。
import os
を追加しなきゃいけなかったから、やめといた。

2020-06-13 13:35 UTC, solaWat commented on notify/notify.py
> +            PythonNotify(f"@{user}" + messege + day.upper(), TOKEN)
別のissueにしよう

2020-06-13 14:06 UTC, KAZYPinkSaurus commented on notify/notify.py
> +            PythonNotify(f"@{user}" + messege + day.upper(), TOKEN)
そうしよう

2020-06-13 14:40 UTC, merged